services:
  gatus:
    image: ghcr.io/twin/gatus:v5.36.0
    container_name: gatus
    restart: always
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CAP_NET_RAW
    environment:
      GATUS_CONFIG_PATH: /config
      GATUS_LOG_LEVEL: INFO
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID:?}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN:?}
    volumes:
      - ./config:/config:ro

networks:
  default:
    name: gatus
    driver_opts:
      com.docker.network.bridge.name: br-gatus
