include = "/run/telemt/config.user.toml"

[general]
use_middle_proxy = false
fast_mode = true

[general.modes]
classic = false
secure = false
tls = true

[server]
port = 443
metrics_port = 9090
metrics_whitelist = ["0.0.0.0/0"]

[server.api]
enabled = true
listen = "0.0.0.0:9091"
whitelist = ["0.0.0.0/0"]
read_only = true
minimal_runtime_enabled = false
minimal_runtime_cache_ttl_ms = 1000

[[server.listeners]]
ip = "0.0.0.0"

[[upstreams]]
type = "direct"
enabled = true
weight = 10
