services:
  beszel:
    image: ghcr.io/henrygd/beszel/beszel:0.18.4
    container_name: beszel
    restart: unless-stopped
    environment:
      APP_URL: http://localhost:8090
    ports:
      - 127.0.0.1:8090:8090
    volumes:
      - ./data:/beszel_data
      - ./socket:/beszel_socket

  beszel-agent:
    image: ghcr.io/henrygd/beszel/beszel-agent:0.18.4-alpine
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    environment:
      LISTEN: /beszel_socket/beszel.sock
      HUB_URL: http://localhost:8090
      KEY: ${PUBLIC_KEY}
      TOKEN: ${TOKEN}
    volumes:
      - ./agent_data:/var/lib/beszel-agent
      - ./socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  default:
    name: beszel
    driver_opts:
      com.docker.network.bridge.name: br-beszel
